Repository scientific-python/spin, pull requests merged in 2023-09, with the labels that each got.

#103 Build as part of run cmd
  spin/cmds/meson.py
Labels: type: Enhancement

#102 Add gdb command from numpy
  .github/workflows/test.yml
  README.md
  example_pkg/pyproject.toml
  spin/cmds/meson.py
Labels: type: Enhancement

#106 Update pre-commit revisions
  .pre-commit-config.yaml
Labels: type: Maintenance

#107 Throughout, invoke build before commands
  .github/workflows/test.yml
  spin/cmds/meson.py
Labels: type: Enhancement

#108 Update classifiers
  pyproject.toml
Labels: type: Maintenance

#109 Ensure `spin run` echoes only command output to stdout
  .github/workflows/test.sh
Labels: type: Maintenance

#110 Update supported Python versions
  .github/workflows/test.yml
  pyproject.toml
Labels: type: Maintenance

#112 Update label check
  .github/workflows/label-check.yaml
Labels: type: Maintenance

#117 Make verbose build also show compiler calls
  spin/cmds/meson.py
Labels: type: Enhancement

#115 Document alternative way of getting debug build
  spin/cmds/meson.py
Labels: type: Documentation

#114 Return single path from _get_site_packages
  .github/workflows/test.sh
  spin/cmds/meson.py
Labels: type: Bug fix

#118 Exit on failed build
  spin/cmds/meson.py
Labels: type: Bug fix

#119 Update ruff
  .pre-commit-config.yaml
Labels: type: Maintenance

#120 Update changelist
  .gitignore
  pyproject.toml
Labels: type: Maintenance

#122 Drop support for Python 3.7
  .github/workflows/test.yml
  pyproject.toml
Labels: type: Maintenance

#124 Also support build sanity check on <3.11
  spin/cmds/meson.py
Labels: type: Enhancement
