Repository scientific-python/spin, pull requests merged in 2023-11, with the labels that each got.

#127 Fix unclosed file warning on debug python
  spin/cmds/meson.py
Labels: type: Bug fix

#134 Add --version
  .github/workflows/test.sh
  pyproject.toml
  spin/__init__.py
  spin/__main__.py
Labels: type: Enhancement

#135 Add alias for help
  spin/__main__.py
Labels: type: Enhancement

#137 Add LLDB (debug) command
  README.md
  example_pkg/pyproject.toml
  spin/cmds/meson.py
Labels: type: Enhancement

#140 Add nox for running tests in an isolated environment
  .github/workflows/test.sh
  .github/workflows/test.yml
  README.md
  noxfile.py
  spin/cmds/build.py
Labels: type: Maintenance

#139 Add pip install with editable mode
  .github/workflows/test.sh
  example_pkg/pyproject.toml
  spin/cmds/pip.py
Labels: type: Enhancement

#142 [DOC] Add install to readme
  README.md
Labels: type: Documentation
