Repository scientific-python/spin, pull requests merged in 2024-07, with the labels that each got.

#215 Update pre-commit
  .pre-commit-config.yaml
Labels: type: Maintenance

#216 Add changelist config
  pyproject.toml
Labels: type: Maintenance

#217 Update ruff config
  .pre-commit-config.yaml
  pyproject.toml
  spin/cmds/meson.py
Labels: type: Maintenance

#218 Update GH actions
  .github/dependabot.yml
  .github/workflows/test.yml
Labels: type: Maintenance

#219 Add codespell pre-commit
  .pre-commit-config.yaml
Labels: type: Maintenance

#220 Update pytest config
  pyproject.toml
Labels: type: Maintenance

#222 Re-activate jobs flag, so nr of CPUs can be tuned back
  spin/cmds/meson.py
Labels: type: Bug fix

#223 Add example of how to test individual tests via nox
  README.md
Labels: type: Documentation

#224 Improve spin docs error message when no build is found
  spin/cmds/meson.py
Labels: type: Enhancement

#225 Make spin install verbose by default
  spin/cmds/pip.py
Labels: type: Enhancement
