Repository scientific-python/spin, pull requests merged in 2024-11, with the labels that each got.

#241 Allow overriding --prefix in spin build
  spin/cmds/meson.py
  spin/tests/test_build_cmds.py
Labels: type: Bug fix

#234 Auto-generate README table of contents
  .pre-commit-config.yaml
  README.md
Labels: type: Documentation

#247 Improve source layout test discovery
  .pre-commit-config.yaml
  example_pkg/example_pkg/_core.pyi
  example_pkg_src/.gitattributes
  example_pkg_src/.gitignore
  example_pkg_src/meson.build
  example_pkg_src/pyproject.toml
  example_pkg_src/src/__init__.py
  example_pkg_src/src/_core.pyi
  example_pkg_src/src/conftest.py
  example_pkg_src/src/coremodule.c
  example_pkg_src/src/meson.build
  example_pkg_src/src/submodule/__init__.py
  example_pkg_src/tests/submodule/test_submodule.py
  example_pkg_src/tests/test_core.py
  spin/cmds/meson.py
  spin/tests/__init__.py
  spin/tests/conftest.py
  spin/tests/test_build_cmds.py
  spin/tests/test_cli.py
  spin/tests/test_editable.py
  spin/tests/test_test.py
Labels: type: Bug fix

#248 Add mechanism for extending existing spin commands
  README.md
  example_pkg/.spin/cmds.py
  example_pkg/pyproject.toml
  spin/__main__.py
  spin/cmds/util.py
  spin/tests/test_extend_command.py
  spin/tests/testutil.py
Labels: type: Enhancement

#246 Let subprocess launched by run handle its own sigint
  spin/cmds/meson.py
Labels: type: Bug fix

#249 Update pre-commit repos
  .pre-commit-config.yaml
Labels: type: Maintenance

#250 Support Python 3.13
  .github/workflows/test.yml
  pyproject.toml
Labels: type: Maintenance

#252 Add metavars for improved docstring rendering
  spin/cmds/meson.py
Labels: type: Documentation

#251 Add pre-import keyword to IPython command
  example_pkg/pyproject.toml
  spin/cmds/meson.py
Labels: type: Enhancement

#253 Correctly colorize uppercase single character flags
  spin/color_format.py
Labels: type: Bug fix

#254 Find correct source for extended commands
  spin/cmds/meta.py
  spin/cmds/util.py
Labels: type: Bug fix
