Repository scientific-python/spin, pull requests merged in 2024-05, with the labels that each got.

#159 Add ``--gcov-report`` flag to ``spin test``
  .github/workflows/test.yml
  README.md
  noxfile.py
  spin/cmds/meson.py
  spin/tests/test_build_cmds.py
Labels: type: Enhancement

#180 Update pre-commit repos
  .pre-commit-config.yaml
Labels: type: Maintenance

#181 Update year
  LICENSE
Labels: type: Maintenance

#155 Allow editable install
  README.md
  example_pkg/pyproject.toml
  spin/cmds/meson.py
  spin/tests/test_build_cmds.py
  spin/tests/test_editable.py
Labels: type: Enhancement

#183 Only add gcov flag when it's specified
  spin/cmds/meson.py
Labels: type: Bug fix

#187 Clarify build cmd docstring
  README.md
  spin/cmds/meson.py
Labels: type: Documentation

#189 Allow older version of meson for testing
  example_pkg/meson.build
Labels: type: Maintenance

#194 `dir_info` metadata field does not exist for conda installs
  spin/cmds/meson.py
Labels: type: Bug fix

#192 Improve debug printing for Meson editable installs
  spin/cmds/pip.py
Labels: type: Enhancement

#191 Use --pyargs to select package to test
  spin/cmds/meson.py
Labels: type: Enhancement

#201 Update ruff configuration
  pyproject.toml
Labels: type: Maintenance

#200 Test lldb on macOS
  spin/tests/test_build_cmds.py
  spin/tests/testutil.py
Labels: type: Maintenance

#197 Provide all command args as keywords
  spin/cmds/meson.py
Labels: type: Maintenance

#198 Print traceback for internal command errors
  spin/__main__.py
Labels: type: Enhancement

#199 docs: allow overriding cleaned directories
  spin/cmds/meson.py
Labels: type: Enhancement

#202 Replace `black` with `ruff format`
  .pre-commit-config.yaml
Labels: type: Maintenance

#206 FIX make sphinx docs work on Windows
  spin/cmds/meson.py
Labels: type: Enhancement
